version: '3.9'

services:
  main_core_app:
    build: 
      context: .
      dockerfile: SSARE/app/Dockerfile
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: SSARE/app
          target: /app
    networks:
      - app_network

    depends_on:
      - scraper_service
      - postgres_service

  scraper_service:
    build: 
      context: .
      dockerfile: SSARE/scraper_service/Dockerfile
    ports:
      - "8081:8081"
    develop:
      watch:
        - action: sync
          path: SSARE/scraper_service
          target: /app

    networks:
      - app_network

  postgres_service:
    build: 
      context: .
      dockerfile: SSARE/postgres_service/Dockerfile
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_network


networks:
  app_network:

volumes:
  core_volume:
  db_volume:
  postgres_data:
