services:
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./core/configs/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - app_network

  main_core_app:
    build: 
      context: ./SSARE
      dockerfile: ./app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./flows:/app/flows
    networks:
      - app_network
    depends_on:
      - scraper_service
      - postgres_service 
      - redis
      - prefect_server
      - prefect_agent

  scraper_service:
    build: 
      context: ./SSARE
      dockerfile: ./scraper_service/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app_network
    depends_on:
      - redis

  qdrant_service:
    build: 
      context: ./SSARE
      dockerfile: ./qdrant_service/Dockerfile
    ports:
      - "6969:6969"
    networks:
      - app_network

  qdrant_storage:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_service/qdrant_storage:/qdrant/data
    networks:
      - app_network

  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ssare_db
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: world
    volumes:
      - ./core/sql_commands:/docker-entrypoint-initdb
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - app_network

  postgres_service:
    build: 
      context: ./SSARE
      dockerfile: ./postgres_service/Dockerfile
    ports:
      - "5434:5434"
    networks:
      - app_network
    depends_on:
      - postgres_db

  nlp_service:
    build: 
      context: ./SSARE
      dockerfile: ./nlp_service/Dockerfile
    restart: always
    ports:
      - "0420:0420"
    networks:
      - app_network
    depends_on:
      - redis
      - postgres_service
    environment:
      - PREFECT_API_URL=http://prefect_server:4200/api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  geo_service:
    build: 
      context: ./SSARE
      dockerfile: ./geo_service/Dockerfile
    restart: always
    ports:
      - "3690:3690"
    networks:
      - app_network
    depends_on:
      - redis
      - postgres_service
      - pelias_placeholder  # Ensure geo_service depends on pelias/placeholder
    environment:
      - PREFECT_API_URL=http://prefect_server:4200/api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  entity_service:
    build: 
      context: ./SSARE
      dockerfile: ./entity_service/Dockerfile
    restart: always
    ports:
      - "1290:1290"
    networks:
      - app_network
    depends_on:
      - redis
      - postgres_service
    environment:
      - PREFECT_API_URL=http://prefect_server:4200/api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pelias_placeholder:
       image: pelias/placeholder
       container_name: pelias_placeholder
       command: "./cmd/server.sh"
       ports:
         - "3000:3000"
       volumes:
         - ./data/placeholder:/data/placeholder  # Adjust this path as necessary
       networks:
         - app_network


  prefect_database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    volumes:
      - ./data/prefect_db/data:/var/lib/postgresql/data
      - ./data/prefect_db/init:/docker-entrypoint-initdb.d
    networks:
      - app_network

  prefect_server:
    image: prefecthq/prefect:2.16-python3.11-conda
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_UI_URL=http://localhost:4200
      - PREFECT_API_URL=http://localhost:4200
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@prefect_database:5432/prefect
      - PREFECT_UI_API_URL=http://localhost:4200/api
    ports:
      - "4200:4200"
    depends_on:
      - prefect_database
    networks:
      - app_network

  prefect_agent:
    image: prefecthq/prefect:2.16-python3.11-conda
    restart: always
    command: prefect worker start -p default
    environment:
      - PREFECT_API_URL=http://prefect_server:4200/api
    networks:
      - app_network
    depends_on:
      - prefect_server
      - scraper_service

  prefect_cli:
    image: prefecthq/prefect:2.16-python3.11-conda
    environment:
      - PREFECT_API_URL=http://prefect_server:4200/api
    networks:
      - app_network
    depends_on:
      - prefect_server
      - prefect_agent

networks:
  app_network:

volumes:
  postgres_data:
  prefect:
  prefect_db: