apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "qdrant-service"
  annotations:
    {{ .Values.qdrant_service.annotations | toYaml | nindent 4}}
spec:
  ingressClassName: {{ .Values.qdrant_service.ingress.className }}
  tls:
    - hosts:
        {{- range .Values.qdrant_service.ingress.hosts }}
        - {{ .host | quote }}
      secretName: {{ .host }}
        {{- end }}
  rules:
    {{- range .Values.qdrant_service.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: "Prefix"
            backend:
              service:
                name: "qdrant-service"
                port:
                  number: 80
    {{- end }}
