apiVersion: v1
kind: Service
metadata:
  name: "postgres-service"
spec:
  type: ClusterIP
  ports:
    - port: 5434
      targetPort: 5434
      protocol: TCP
      name: http
  selector:
    app: "postgres-service"
