apiVersion: apps/v1
kind: Deployment
metadata:
  name: "scraper"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "scraper"
  template:
    metadata:
      labels:
        app: "scraper"
    spec:
      serviceAccountName: "ssare"
      containers:
        - name: "scraper"
          image: "{{ .Values.scraper.image.repository }}:{{ .Values.scraper.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http