apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nlp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nlp"
  template:
    metadata:
      labels:
        app: "nlp"
    spec:
      serviceAccountName: "ssare"
      containers:
        - name: "nlp"
          image: "{{ .Values.nlp.image.repository }}:{{ .Values.nlp.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 420
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 420
          readinessProbe:
            httpGet:
              path: /healthz
              port: 420