apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres-storage
spec:
  teamId: "ssare"
  volume:
    size: 1Gi
    storageClass: {{ .Values.postgres_storage.storage.storageClass }}
  numberOfInstances: 1
  users:
    {{ .Values.postgres_storage.username }}:
    - superuser
  databases:
    {{ .Values.postgres_storage.database }}: "{{ .Values.postgres_storage.username }}"
  preparedDatabases:
    {{ .Values.postgres_storage.database }}: { }
  postgresql:
    version: "15"