apiVersion: apps/v1
kind: Deployment
metadata:
  name: "redis"
spec:
  selector:
    matchLabels:
      app: "redis"
  replicas: 1
  template:
    metadata:
      labels:
        app: "redis"
    spec:
      serviceAccountName: "ssare"
      volumes:
        - name: "redis-data"
          persistentVolumeClaim:
            claimName: "redis-data"
            readOnly: false
      containers:
        - name: "redis"
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 3
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: "/data"
              name: redis-data
              readOnly: false

