apiVersion: apps/v1
kind: Deployment
metadata:
  name: "main-core-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "main-core-app"
  template:
    metadata:
      labels:
        app: "main-core-app"
    spec:
      serviceAccountName: "ssare"
      containers:
        - name: "main-core-app"
          image: "{{ .Values.main_core_app.image.repository }}:{{ .Values.main_core_app.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http