apiVersion: v1
kind: Service
metadata:
  name: "main-core-app"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "main-core-app"
