name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image for App
        run: |
          cd SSARE
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/main_core_app:${{ github.sha }} -f ./app/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/main_core_app:${{ github.sha }} && \
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/main_core_app:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/main_core_app:latest && \
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/main_core_app:latest

      - name: Build and Push Docker Image for Scraper Service
        run: |
          cd SSARE
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/scraper_service:${{ github.sha }} -f ./scraper_service/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/scraper_service:${{ github.sha }} && \
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/scraper_service:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/scraper_service:latest && \
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/scraper_service:latest

      - name: Build and Push Docker Image for Postgres Service
        run: |
          cd SSARE
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/postgres_service:${{ github.sha }} -f ./postgres_service/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/postgres_service:${{ github.sha }} && \
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/postgres_service:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/postgres_service:latest && \
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/postgres_service:latest
