name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build and Push Docker Image for Main Core App
      run: |
          docker build -t SSARE/core_app:${{ github.sha }} ./scraper
          docker push SSARE/core_app:${{ github.sha }}
    - name: Build and Push Docker Image for Scraper Service
      run: |
        docker build -t SSARE/scraper_service:${{ github.sha }} ./scraper
        docker push SSARE/scraper_service:${{ github.sha }}
    - name: Build and Push Docker Image for Processor Service
      run: |
        docker build -t SSARE/postgres_service:${{ github.sha }} ./processor
        docker push SSARE/postgres_service:${{ github.sha }}